package org.cce.sistema.model;
// Generated 24/06/2020 10:23:40 AM by Hibernate Tools 5.3.15.Final



/**
 * Bautismo generated by hbm2java
 */
public class Bautismo  implements java.io.Serializable {


     private Integer idBautismo;
     private String parroquia;
     private String lugar;

    public Bautismo() {
    }

    public Bautismo(String parroquia, String lugar) {
       this.parroquia = parroquia;
       this.lugar = lugar;
    }
   
    public Integer getIdBautismo() {
        return this.idBautismo;
    }
    
    public void setIdBautismo(Integer idBautismo) {
        this.idBautismo = idBautismo;
    }
    public String getParroquia() {
        return this.parroquia;
    }
    
    public void setParroquia(String parroquia) {
        this.parroquia = parroquia;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }




}


