package org.cce.sistema.model;
// Generated 24/06/2020 10:23:40 AM by Hibernate Tools 5.3.15.Final


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Catequizado generated by hbm2java
 */
public class Catequizado  implements java.io.Serializable {


     private Integer idCatequizado;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String telefono;
     private String correo;
     private Date fechaNacimiento;
     private Date fechaAlta;
     private byte[] foto;
     private String nombrePapa;
     private String nombreMama;
     private String estadoRegistro;
     private String estado;
     private String observaciones;
     private Integer idDireccion;
     private Integer idCodigo;
     private Integer idMunicipio;
     private Integer idBautismo;
     private Integer idNumero;
     private Set registros = new HashSet(0);

    public Catequizado() {
    }

    public Catequizado(String nombre, String apellidoPaterno, String apellidoMaterno, String telefono, String correo, Date fechaNacimiento, Date fechaAlta, byte[] foto, String nombrePapa, String nombreMama, String estadoRegistro, String estado, String observaciones, Integer idDireccion, Integer idCodigo, Integer idMunicipio, Integer idBautismo, Integer idNumero, Set registros) {
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.telefono = telefono;
       this.correo = correo;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaAlta = fechaAlta;
       this.foto = foto;
       this.nombrePapa = nombrePapa;
       this.nombreMama = nombreMama;
       this.estadoRegistro = estadoRegistro;
       this.estado = estado;
       this.observaciones = observaciones;
       this.idDireccion = idDireccion;
       this.idCodigo = idCodigo;
       this.idMunicipio = idMunicipio;
       this.idBautismo = idBautismo;
       this.idNumero = idNumero;
       this.registros = registros;
    }
   
    public Integer getIdCatequizado() {
        return this.idCatequizado;
    }
    
    public void setIdCatequizado(Integer idCatequizado) {
        this.idCatequizado = idCatequizado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getNombrePapa() {
        return this.nombrePapa;
    }
    
    public void setNombrePapa(String nombrePapa) {
        this.nombrePapa = nombrePapa;
    }
    public String getNombreMama() {
        return this.nombreMama;
    }
    
    public void setNombreMama(String nombreMama) {
        this.nombreMama = nombreMama;
    }
    public String getEstadoRegistro() {
        return this.estadoRegistro;
    }
    
    public void setEstadoRegistro(String estadoRegistro) {
        this.estadoRegistro = estadoRegistro;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Integer getIdDireccion() {
        return this.idDireccion;
    }
    
    public void setIdDireccion(Integer idDireccion) {
        this.idDireccion = idDireccion;
    }
    public Integer getIdCodigo() {
        return this.idCodigo;
    }
    
    public void setIdCodigo(Integer idCodigo) {
        this.idCodigo = idCodigo;
    }
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }
    public Integer getIdBautismo() {
        return this.idBautismo;
    }
    
    public void setIdBautismo(Integer idBautismo) {
        this.idBautismo = idBautismo;
    }
    public Integer getIdNumero() {
        return this.idNumero;
    }
    
    public void setIdNumero(Integer idNumero) {
        this.idNumero = idNumero;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


