package org.cce.sistema.model;
// Generated 24/06/2020 10:23:40 AM by Hibernate Tools 5.3.15.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Ciclo generated by hbm2java
 */
public class Ciclo  implements java.io.Serializable {


     private Integer idCiclo;
     private String nombre;
     private Boolean estatus;
     private Set registros = new HashSet(0);

    public Ciclo() {
    }

    public Ciclo(String nombre, Boolean estatus, Set registros) {
       this.nombre = nombre;
       this.estatus = estatus;
       this.registros = registros;
    }
   
    public Integer getIdCiclo() {
        return this.idCiclo;
    }
    
    public void setIdCiclo(Integer idCiclo) {
        this.idCiclo = idCiclo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Boolean getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Boolean estatus) {
        this.estatus = estatus;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


