package org.cce.sistema.model;
// Generated 24/06/2020 10:23:40 AM by Hibernate Tools 5.3.15.Final



/**
 * Numero generated by hbm2java
 */
public class Numero  implements java.io.Serializable {


     private Integer idNumero;
     private Integer numeroCasa;

    public Numero() {
    }

    public Numero(Integer numeroCasa) {
       this.numeroCasa = numeroCasa;
    }
   
    public Integer getIdNumero() {
        return this.idNumero;
    }
    
    public void setIdNumero(Integer idNumero) {
        this.idNumero = idNumero;
    }
    public Integer getNumeroCasa() {
        return this.numeroCasa;
    }
    
    public void setNumeroCasa(Integer numeroCasa) {
        this.numeroCasa = numeroCasa;
    }




}


