package org.cce.sistema.model;
// Generated 24/06/2020 10:23:40 AM by Hibernate Tools 5.3.15.Final


import java.util.HashSet;
import java.util.Set;

/**
 * Parroquia generated by hbm2java
 */
public class Parroquia  implements java.io.Serializable {


     private Integer idParroquia;
     private String diocesis;
     private String decanato;
     private String parroquia;
     private String presbitero;
     private byte[] logo;
     private Set registros = new HashSet(0);

    public Parroquia() {
    }

    public Parroquia(String diocesis, String decanato, String parroquia, String presbitero, byte[] logo, Set registros) {
       this.diocesis = diocesis;
       this.decanato = decanato;
       this.parroquia = parroquia;
       this.presbitero = presbitero;
       this.logo = logo;
       this.registros = registros;
    }
   
    public Integer getIdParroquia() {
        return this.idParroquia;
    }
    
    public void setIdParroquia(Integer idParroquia) {
        this.idParroquia = idParroquia;
    }
    public String getDiocesis() {
        return this.diocesis;
    }
    
    public void setDiocesis(String diocesis) {
        this.diocesis = diocesis;
    }
    public String getDecanato() {
        return this.decanato;
    }
    
    public void setDecanato(String decanato) {
        this.decanato = decanato;
    }
    public String getParroquia() {
        return this.parroquia;
    }
    
    public void setParroquia(String parroquia) {
        this.parroquia = parroquia;
    }
    public String getPresbitero() {
        return this.presbitero;
    }
    
    public void setPresbitero(String presbitero) {
        this.presbitero = presbitero;
    }
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }
    public Set getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set registros) {
        this.registros = registros;
    }




}


